language: elixir
elixir: 1.2.1
services:
- postgres
otp_release:
- 18.0
sudo: false
before_script:
- psql -c 'create database elixircast_test;' -U postgres
- mix deps.get --only test
- echo -e "Host dokku.deanbrophy.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- mix test
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 deploy_key
- ssh-add deploy_key
- git remote add deploy root@dokku.deanbrophy.com:elixircast
- git push deploy
before_install:
- openssl aes-256-cbc -K $encrypted_fb52623ab7c7_key -iv $encrypted_fb52623ab7c7_iv
  -in deploy_key.enc -out deploy_key -d
