language: elixir
elixir: 1.2.1
services:
- postgres
otp_release:
- 18.0
sudo: false
before_script:
- psql -c 'create database elixircast_test;' -U postgres
- mix deps.get --only test
script:
- mix test
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 deploy_key
- mv deploy_key id_rsa && mv id_rsa ~/.ssh
- cp key_config ~/.ssh/config
- ssh-add ~/.ssh/id_rsa
- git config --global push.default simple
- git remote add dokku dokku@dokku.deanbrophy.com:elixircast
- git branch -u dokku/master master
- git push dokku
before_install:
- openssl aes-256-cbc -K $encrypted_fb52623ab7c7_key -iv $encrypted_fb52623ab7c7_iv
  -in deploy_key.enc -out deploy_key -d
