language: elixir
elixir: 1.2.1
services:
- postgres
otp_release:
- 18.0
sudo: false
before_script:
- psql -c 'create database elixircast_test;' -U postgres
- mix deps.get --only test
script:
- mix test
after_success:
- eval "$(ssh-agent -s)"
- pwd
- mv .trav/ssh-config ~/.ssh/config
- chmod 600 deploy_key
- ssh-add deploy_key
- git remote add deploy root@dokku.deanbrophy.com:elixircast
- git push deploy
dd:
- openssl aes-256-cbc -K $encrypted_cf0e4d88cdc5_key -iv $encrypted_cf0e4d88cdc5_iv
  -in deploy_key.enc -out deploy_key -d
